# Generated by Django 3.2.2 on 2021-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
